version: '3.8'

services:
  db:
    image: postgres:13.11-alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=ja_JP.UTF-8'
      TZ: Asia/Tokyo
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    hostname: postgres

  api:
    image: bookan-backend:v1
    command: sh -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    volumes:
      - .:/app
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - db

volumes:
  postgres_volume:
